CREATE DATABASE PROJECT2
select  * FROM Location
select * from fact
select * from Product;
1. Number of states in LocationTable
SELECT COUNT(DISTINCT State) AS NumberOfStates
FROM Location;

2. Number of products of Regular type
SELECT COUNT(*) AS RegularProducts
FROM Product
WHERE Type = 'Regular';

3. Total marketing spending for ProductID 1
SELECT SUM(Marketing) AS TotalMarketing
FROM Fact
WHERE ProductID = 1;

4. Minimum sales of a product
SELECT MIN(Sales) AS MinimumSales
FROM Fact;

5. Maximum COGS
SELECT MAX(COGS) AS MaximumCOGS
FROM Fact;

6. Details of products where Product Type is Coffee

SELECT * FROM Product
WHERE Product_Type = 'Coffee';

7. Details where Total Expenses are greater than 40
SELECT * FROM Fact
WHERE Total_Expenses > 40;

8. Average sales in Area Code 719
SELECT AVG(Sales) AS AverageSales
FROM Fact
WHERE Area_Code = 719;

9. Total profit generated by Colorado
SELECT SUM(F.Profit) AS TotalProfit
FROM Fact F
JOIN Location L
    ON F.Area_Code = L.Area_Code
WHERE L.State = 'Colorado';

10. Average inventory for each Product ID
SELECT ProductID, AVG(Inventory) AS AverageInventory
FROM Fact
GROUP BY ProductID;

11. Display states in sequential order
SELECT * FROM Location
ORDER BY State ASC;

12. Average budget where average budget margin is greater than 100 Assuming Budget and Budget Margin are columns in FactTable:

SELECT ProductID,
       AVG(Budget_Profit) AS AverageBudget,
       AVG(Budget_Margin) AS AverageBudgetMargin
FROM Fact
GROUP BY ProductID
HAVING AVG(Budget_Margin) > 100;

13. Total sales on 2010-01-01
SELECT SUM(Sales) AS TotalSales
FROM Fact
WHERE Date = '2010-01-01';

14. Average total expense of each Product ID on each date
SELECT Date,
       ProductID,
       AVG(Total_Expenses) AS AverageTotalExpense
FROM Fact
GROUP BY Date, ProductID
ORDER BY Date, ProductID;

15. Display the requested attributes
SELECT F.Date, F.ProductID, P.Product_Type,P.Product, F.Sales,F.Profit, L.State, F.Area_Code
FROM Fact F
JOIN Product P
    ON F.ProductID = P.ProductID
JOIN Location L
    ON F.Area_Code = L.Area_Code;

16. Sales-wise rank without gaps
SELECT ProductID,Sales,
       DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank
FROM Fact;

17. State-wise profit and sales
SELECT L.State,SUM(F.Profit) AS TotalProfit,SUM(F.Sales) AS TotalSales
FROM Fact F
JOIN Location L
    ON F.Area_Code = L.Area_Code
GROUP BY L.State
ORDER BY L.State;

18. State-wise profit and sales along with product name
SELECT L.State,P.Product,
       SUM(F.Profit) AS TotalProfit,
       SUM(F.Sales) AS TotalSales
FROM Fact F
JOIN Location L
    ON F.Area_Code = L.Area_Code
JOIN Product P
    ON F.ProductID = P.ProductID
GROUP BY L.State, P.Product
ORDER BY L.State, P.Product;

19. Calculate sales after a 5% increase
SELECT ProductID,Sales,
       Sales * 1.05 AS IncreasedSales
FROM Fact;

20. Maximum profit with Product ID and Product Type
SELECT F.ProductID,P.Product_Type, F.Profit
FROM Fact F
JOIN Product P
    ON F.ProductID = P.ProductID
WHERE F.Profit = (
    SELECT MAX(Profit)
    FROM Fact
);

21. Profit or Loss based on Total Expenses
If total expenses are less than 60, classify it as Profit; otherwise Loss:

SELECT ProductID,
       Total_Expenses,
       CASE
           WHEN Total_Expenses < 60 THEN 'Profit'
           ELSE 'Loss'
       END AS Result
FROM Fact;
select * from Fact
23. Weekly sales using ROLLUP
To calculate weekly sales with date and Product ID hierarchy:

SELECT
    DATEPART(YEAR, Date) AS SalesYear,
    DATEPART(WEEK, Date) AS SalesWeek,
    Date,
    ProductID,
    SUM(Sales) AS TotalSales
FROM Fact

GROUP BY ROLLUP (
    DATEPART(YEAR, Date),
    DATEPART(WEEK, Date),
    Date,
    ProductID
)
ORDER BY SalesYear, SalesWeek, Date, ProductID;

24. Change Product Type from Coffee to Tea for Product ID 1, then undo it

BEGIN TRANSACTION;

UPDATE Product
SET Product Type = 'Tea'
WHERE ProductID = 1
  AND Product Type = 'Coffee';

-- Check the change
SELECT * FROM Product
WHERE ProductID = 1;

-- Undo the change
ROLLBACK TRANSACTION;

ROLLBACK undoes the update, so the original Coffee value is restored.

25. Display Date, Product ID and Sales where Total Expenses are between 100 and 200
SELECT Date,ProductID,Sales FROM Fact
WHERE Total_Expenses BETWEEN 100 AND 200;

BETWEEN includes both 100 and 200.

26. Delete records from ProductTable where type is Regular
DELETE FROM Product
WHERE Type = 'Regular';

BEGIN TRANSACTION;

DELETE FROM Product
WHERE Type = 'Regular';

-- Check the result
SELECT *
FROM Product;

-- Undo if needed
ROLLBACK TRANSACTION;

29. Display the ASCII value of the fifth character from Product
In SQL Server, use ASCII() with SUBSTRING():

SELECT Product,
       ASCII(SUBSTRING(Product, 5, 1)) AS ASCIIValue
FROM Product;




